### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/Polygon-Map-Generation#1]
some ideas,

- [ ] cleanup scripts (now everything happens in PolygonMapDebugView.cs)
- [ ] add placeholder tiles ground materials (with proper corner tiles and transition tiles from biome A to biome B)
- [ ] add UI for runtime generation
- [ ] add procedural roads overlay generator
- [ ] add procedural foliage layer generator
- [ ] add procedural area names generator
- [ ] add procedural building generator
- [ ] add dungeon entrances
- [ ] add procedural dungeon generator
- [ ] make it as a webgl compatible map generator (and some export options, to unity tilemap)
- [ ] optimize
- [ ] add this for generating villages? https://github.com/twobob/TownGenerator
- [ ] and more..
